### ISSUE TITLE
Trying to calculate order parameter for POPC.

### ISSUE THREAD

**Issue by sathishdasari** [NMRLipids/MATCH#97]
Hi, 
I ran a lipid bilayer simulation for 500 ns and when I am trying to calculate order parameter for POPC for a trajectory beginning from the simulation it runs fine. But I want to consider the last 250ns trajectory discarding the first 250ns as equilibration. When I use the pbc trajectory for the last 250 ns I get the following error.

Reading OP definitions ...

Reading trajectories and calculating OPs ...

Traceback (most recent call last):
  File "/home/sathish/curli/lipid/charmm-gui-9790619360/gromacs/POPC_order/calcOrderParameters.py", line 278, in <module>
    read_trajs_calc_OPs(ordPars, opts.top_fname, trajs)
  File "/home/sathish/curli/lipid/charmm-gui-9790619360/gromacs/POPC_order/calcOrderParameters.py", line 184, in read_trajs_calc_OPs
    mol = mda.Universe(top, trajs)
  File "/home/sathish/miniconda3/lib/python3.9/site-packages/MDAnalysis/core/universe.py", line 375, in __init__
    self.load_new(coordinates, format=format, in_memory=in_memory,
  File "/home/sathish/miniconda3/lib/python3.9/site-packages/MDAnalysis/core/universe.py", line 580, in load_new
    self.trajectory = reader(filename, format=format, **kwargs)
  File "/home/sathish/miniconda3/lib/python3.9/site-packages/MDAnalysis/lib/util.py", line 2544, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sathish/miniconda3/lib/python3.9/site-packages/MDAnalysis/coordinates/chain.py", line 278, in __init__
    self.n_atoms = self._get_same('n_atoms')
  File "/home/sathish/miniconda3/lib/python3.9/site-packages/MDAnalysis/coordinates/chain.py", line 528, in _get_same
    value = values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
conc: 0
sed: can't read OrdPars.dat.line: No such file or directory

**Comment by ohsOllila** [comment]
Hi,

this repository (https://github.com/NMRLipids/MATCH) was a preliminary version of the NMRlipids databank which is now located at https://github.com/NMRLipids/Databank. For more documentation see https://nmrlipids.github.io/index.html. 

Currently it works such that you need to add the simulation in the databank and run analyses following these instructions https://nmrlipids.github.io/addingData.html. Then you will have the order parameters for your system available in the databank. We do not currently have instructions available to calculate order parameters without adding data into Zenodo first, but that is also possible in principle.
